### ISSUE TITLE
-c --class doesn't work due to getopt quoting

### ISSUE THREAD

**Issue by gandalf3** [Schweber/hdrop#1]
using `hdrop --class xyz` causes hdrop to search for the class `'xyz'` (with single quotes), which doesn't match..

passing the `-u` `--unquoted` flag to getopt invocation on [line 120](https://github.com/Schweber/hdrop/blob/f05ffc86bbad69bfe52d6af17c6353dd9f88233e/hdrop#L120) fixes it for me

```
getopt --version
getopt from util-linux 2.39.3
```

**Comment by Schweber** [comment]
Thank you! I implemented your fix.
